export const variants = {
  primary: [
    { backgroundColor: '#000' },
    { color: '#fff' },
    { height: 36 },
    { paddingLeft: 12 },
    { paddingRight: 12 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
  ],
  secondary: [
    { backgroundColor: '#f1f1f3' },
    { color: '#000' },
    { height: 36 },
    { flex: 1 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  destructive: [
    { backgroundColor: '#d10e1d' },
    { color: '#fff' },
    { height: 36 },
    { flex: 1 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  outline: [
    { backgroundColor: '#fff' },
    { color: '#000' },
    { borderColor: '#cfcfcf' },
    { darkBorderColor: '#2f2f2f' },
    { borderWidth: 1 },
    { height: 36 },
    { flex: 1 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  link: [
    { height: 36 },
    { borderBottomWidth: 1 },
    { borderBottomColor: '#9f9f9f' },
  ],
};

export const darkVariants = {
  primary: [
    { backgroundColor: '#fff' },
    { color: '#000' },
    { height: 36 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  secondary: [
    { backgroundColor: '#f1f1f3' },
    { color: '#000' },
    { height: 36 },
    { flex: 1 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  destructive: [
    { backgroundColor: '#d10e1d' },
    { color: '#fff' },
    { height: 36 },
    { flex: 1 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  outline: [
    { backgroundColor: '#000' },
    { color: '#000' },
    { borderColor: '#7f7f7f' },
    { borderWidth: 1 },
    { height: 36 },
    { flex: 1 },
    { borderRadius: 8 },
    { justifyContent: 'center' },
    { alignItem: 'center' },
    { paddingLeft: 12 },
    { paddingRight: 12 },
  ],
  link: [
    { height: 36 },
    { borderBottomWidth: 1 },
    { borderBottomColor: '#9f9f9f' },
  ],
};

export const textVariant = {
  primary: [{ color: '#fff' }, { darkColor: '#000' }, { textAlign: 'center' }],
  secondary: [
    { color: '#000' },
    { darkColor: '#fff' },
    { textAlign: 'center' },
  ],
  destructive: [
    { color: '#fff' },
    { darkColor: '#fff' },
    { textAlign: 'center' },
  ],
  outline: [{ color: '#000' }, { darkColor: '#fff' }, { textAlign: 'center' }],
  link: [{ color: '#000' }, { textAlign: 'center' }],
};
export const darkTextVariant = {
  primary: [{ color: '#000' }, { textAlign: 'center' }],
  secondary: [{ color: '#000' }, { textAlign: 'center' }],
  destructive: [{ color: '#fff' }, { textAlign: 'center' }],
  outline: [{ color: '#fff' }, { textAlign: 'center' }],
  link: [{ color: '#fff' }, { textAlign: 'center' }],
};
